singleRecord: false
regionsSelector: null
recordSelector: null
recordxpath: null
fields:
  - name: prodURL
    singleValue: false
    description: the url of a page present on the sitemap page
    xpath: //div[@id="prodURL"]//li
 
