singleRecord: false
regionsSelector: null
recordSelector: null
recordXPath: null
fields:
  - name: product_image
    xpath: //img[@class="pdp-gallery__main-image"]/@src
    regExp: (.*)_(\d+)x(\d+)(.*)
    regExpReplace: $1_460x460$4
    singleValue: true
  - name: keywords
    singleValue: true
  - name: download_time
    singleValue: true
  - name: url
    xpath: //link[@rel="canonical"]/@href
    singleValue: true
  - name: category
    singleValue: true
  - name: sub_category
    singleValue: true
  - name: product_description
    xpath: //meta[@name="description"]/@content
    singleValue: true
  - name: online_price
    xpath: //p[@class="price--per"]
    regExp: ^.*€
    singleValue: true
  - name: online_price_currency
    singleValue: true
  - name: availability
    singleValue: true
  - name: in_store_price
    singleValue: true
  - name: in_store_price_currency
    singleValue: true
  - name: additional_description
    singleValue: true
  - name: ingredients_list
    xpath: //h5[contains(@class, "product-description__feature-title")]/following-sibling::div[@class="product-description__feature-values"]/span
    singleValue: true
  - name: brand
    singleValue: true
  - name: manufacturer_name
    singleValue: true
  - name: size
    singleValue: true
  - name: net_weight
    singleValue: true
  - name: gross_weight
    singleValue: true
  - name: upc
    singleValue: true
  - name: asin
    singleValue: true
  - name: hidden_upc
    singleValue: true
  - name: sku_number
    singleValue: true
  - name: retailer_product_code
    singleValue: true
  - name: directions_information
    singleValue: true
  - name: warnings
    singleValue: true
  - name: secondary_image
    singleValue: true
  - name: number_of_customer_reviews
    xpath: //span[@itemprop="reviewCount"]
    singleValue: true
  - name: customer_review_rating
    xpath: //a[@class="offer-selector__rating"]//meter[@itemprop="ratingValue"]/@value
    singleValue: true
  - name: aplus_images
    singleValue: true
  - name: category_ranking
    singleValue: true
  - name: shipping_details
    singleValue: true
  - name: shipping_dimensions
    singleValue: true
  - name: specifications
    singleValue: true
  - name: shipping_weight
    singleValue: true
  - name: warranty
    singleValue: true
  - name: ean_gtin
    xpath: //span[contains(text(),"EAN")]/following-sibling::div[@class="product-description__feature-values"]
    regExp: \/\s(\d+)
    regExpReplace: $1
    singleValue: true
  - name: storage
    xpath: //h5[contains(text(),"Conservation")]/following-sibling::div/span
    singleValue: true
  - name: country_of_origin
    xpath: //span[contains(@class,"product-description__feature-label") and contains(text(),"Origine:")]/following-sibling::div/span
    singleValue: true
  - name: allergy_advice
    singleValue: true
  - name: recycling_information
    singleValue: true
  - name: salt_per_serving
    singleValue: true
  - name: salt_per_serving_uom
    singleValue: true
  - name: serving_size_2
    singleValue: true
  - name: serving_size_2_uom
    singleValue: true
  - name: dietary_information
    singleValue: true
  - name: product_other_information
    singleValue: true
  - name: packaging
    singleValue: true
  - name: additives
    singleValue: true
  - name: footer_product_info
    singleValue: true
  - name: award_symbol
    singleValue: true
  - name: drive
    singleValue: true
  - name: enhanced_content
    singleValue: true
  - name: retailer_category
    singleValue: true
  - name: retailer_subcategory
    singleValue: true
  - name: additional_desc_bullet_count
    singleValue: true
  - name: video
    singleValue: true
  - name: coupons
    singleValue: true
  - name: products_per_page
    singleValue: true
  - name: retailer_id
    singleValue: true
  - name: addon_item
    singleValue: true
  - name: syndicated_data
    singleValue: true
  - name: harvested_price
    singleValue: true
  - name: price_per_unit
    singleValue: true
  - name: price_per_unit_uom
    singleValue: true
  - name: scrape_code
    singleValue: true
  - name: image_alt_text
    singleValue: true
  - name: promotion
    singleValue: true
  - name: harvested_review_rating
    singleValue: true
  - name: extended_product_description
    singleValue: true
  - name: rpc_sku_hybrid
    singleValue: true
  - name: lbb
    singleValue: true
  - name: lbb_price
    singleValue: true
  - name: feature_bullets
    singleValue: true
  - name: pack_size
    singleValue: true
  - name: secondary_image_total
    singleValue: true
  - name: news
    singleValue: true
  - name: other_sellers_name
    singleValue: true
  - name: other_sellers_price
    singleValue: true
  - name: other_sellers_shipping
    singleValue: true
  - name: coupon_discount_percentage
    singleValue: true
  - name: coupon_on_full_page_text
    singleValue: true
  - name: brand_url
    singleValue: true
  - name: international_shipping
    singleValue: true
  - name: sales_rank
    singleValue: true
  - name: sales_rank_category
    singleValue: true
  - name: subscription_price
    singleValue: true
  - name: subscribe_and_save
    singleValue: true
  - name: hero_quick_promo_headline
    singleValue: true
  - name: hero_quick_promo_image_url
    singleValue: true
  - name: hero_quick_promo_url
    singleValue: true
  - name: pasin
    singleValue: true
  - name: video_length
    singleValue: true
  - name: other_sellers_prime
    singleValue: true
  - name: prime_note
    singleValue: true
  - name: deal_price
    singleValue: true
  - name: ingredient_image_present
    singleValue: true
  - name: fact_image_present
    singleValue: true
  - name: large_image_count
    singleValue: true
  - name: variant_asins
    singleValue: true
  - name: andon_cord
    singleValue: true
  - name: prime_flag
    singleValue: true
  - name: list_price
    singleValue: true
  - name: alcohol_content
    singleValue: true
  - name: stock_number
    singleValue: true
  - name: sales_volume_per_month
    singleValue: true
  - name: legal_disclaimer
    singleValue: true
  - name: mpc
    singleValue: true
  - name: drive_id
    singleValue: true
  - name: harvested_list_price
    singleValue: true
  - name: in_store_availability
    singleValue: true
  - name: harvested_product_description
    singleValue: true
  - name: new_version
    singleValue: true
  - name: new_asin
    singleValue: true
  - name: new_description
    singleValue: true
  - name: variant_information
    singleValue: true
  - name: first_variant
    singleValue: true
  - name: variants
    singleValue: true
  - name: platform
    singleValue: true
  - name: additional_desc_bullet_info
    singleValue: true
  - name: magnesium_per_serving
    singleValue: true
  - name: magnesium_per_serving_uom
    singleValue: true
  - name: amazon_choice
    singleValue: true
  - name: amazon_choice_text
    singleValue: true
  - name: deal_type
    singleValue: true
  - name: Prop_65_warning
    singleValue: true
  - name: allergy_information
    singleValue: true
  - name: product_id
    xpath: //div[@id="product_id"]/@productId
    singleValue: true
  - name: Shipping_Information
    singleValue: true
  - name: colour
    singleValue: true
  - name: colour_ref
    singleValue: true
  - name: fast_track
    singleValue: true
  - name: supplementary_image
    singleValue: true
  - name: supplementary_image_total
    singleValue: true
  - name: age_suitability  
    singleValue: true
  - name: energy_efficiency
    singleValue: true
  - name: technical_information_pdf_present
    singleValue: true
  - name: t_&_cs
    singleValue: true
  - name: privacy_policy
    singleValue: true
  - name: customer_service_availability
    singleValue: true
  - name: materials
    singleValue: true
  - name: 360_image_present
    singleValue: true
  - name: image_zoom_feature_present
    singleValue: true