
fields:
- name: mediaImage
	singleValue: true
  description: image collected
- name: isBanner
  singleValue: true
  description:
  type: BOOLEAN
- name: isCarousel
	singleValue: true
  description:
  type: BOOLEAN
- name: isTop
	singleValue: true
  description:
  type: BOOLEAN
- name: isBottom
	singleValue: true
  description:
  type: BOOLEAN
- name: isFullWidth
	singleValue: true
  description:
  type: BOOLEAN
- name: isFullHeight
	singleValue: true
  description:
  type: BOOLEAN
- name: isLeft
	singleValue: true
  description:
  type: BOOLEAN
- name: isRight
	singleValue: true
  description:
  type: BOOLEAN
- name: isMiddle
	singleValue: true
  description:
  type: BOOLEAN
- name: isDropDown
	singleValue: true
  description:
  type: BOOLEAN
- name: isCategory
	singleValue: true
  description:
  type: BOOLEAN
- name: isPlaceHolder
	singleValue: true
  description:
  type: BOOLEAN
- name: hasPromo
	singleValue: true
  description:
  type: BOOLEAN
- name: isSponsoredProduct
	singleValue: true
  description:
  type: BOOLEAN