
fields:
# extra GEO fields
- name: onlineStore
  singleValue: true
  description: store name
- name: drive
  singleValue: true
  description: Postcode/Drive of the store to identifyPostcode/Drive of the store - To identify which postcode for a certain retailer.
- name: driveId
  singleValue: true
  description: 
- name: retailerID
  singleValue: true
  description: Store number - To identify which store for a certain retailer.

# product/core use same xpath as within core
- name: image
  singleValue: true
  description: URL of the main product image
- name: category
  singleValue: false
  description: The categories (e.g. from breadcrumbs)
- name: nameExtended
  singleValue: true
  description: The product name, prefixing "${brand} - " if not included in "name" and appending " - ${variantType}" if necessary (fixed per feed)
- name: listPrice
  singleValue: true
  description: The stated undiscounted price for the product
- name: price
  singleValue: true
  description: The offered price for the selected product variant - if a user clicks add to basket this is the price they would be charged
- name: availabilityText
  singleValue: true
  description: Availability as described on page for the selected variant. If there is no availability but the product can be added to cart, this field should be "In Stock"
  regExp: (.+)
  regExpReplace: In Stock
  defaultValue: Out of Stock
- name: brandText
  singleValue: true
  description: Product brand shown - this may actually NOT be just a brand name, e.g. "Visit the Gillette Store"
- name: manufacturer
  singleValue: true
  description: Product manufacturer
- name: quantity
  singleValue: true
  description: Quantity as described on the page
  regExp: (?:\s?([\d\.]+\s?)([bB]ar[s]?|[cC]ount|[cC]t|[fF][lL][\.]?\s?[oO][zZ][\.]?|FO|[mM][lL]|[oO][zZ][\.]?|pc|[pP]int|[pP]ops|qt|[wW]ipe[s]?).?)$|(?:\s?([\d\.]+\s?)([bB]ar[s]?|[cC]ount|[cC]|[fF][lL][\.]?\s?[oO][zZ][\.]?|FO|[mM][lL]|[oO][zZ][\.]?|pc|[pP]int|[pP]ops|qt|[wW]ipe[s]?).?\s?[\&\-\w\s]+)$
  regExpReplace: $1$2$3$4
- name: gtin
  singleValue: true
  description: GTIN code (includes UPC/EAN)
- name: sku
  singleValue: true
  description: The store-specific product identifier
- name: variantId
  singleValue: true
  description: Identifier for a variant from a store where variants share the same sku
- name: asin
  singleValue: true
  description: 
- name: promotion
  singleValue: true
  description: promotion text on product page
