recordXPath: //div[@id="my-urls"]//ul/li
fields:
  - name: paginationUrl
    singleValue: false
    description: desired url to pass in chain
    xpath: //text()
  - name: resultsCount
    singleValue: false
    description: total number of results
    xpath: ancestor::html//div[@id="my-results-count"]